/**
 * main.jsx — application bootstrap.
 *
 * Registers the Vite PWA service worker (generated by vite-plugin-pwa).
 * Service worker handles offline caching of the app shell.
 */
import React from 'react'
import ReactDOM from 'react-dom/client'
import { registerSW } from 'virtual:pwa-register'
import App from './App'
import './index.css'

// Register PWA service worker.
// updateSW() is called automatically when a new version is deployed.
registerSW({
  onNeedRefresh() {
    // In a future iteration: show a "New version available — reload" toast
    console.info('[PWA] New content available, refresh to update')
  },
  onOfflineReady() {
    console.info('[PWA] App is ready for offline use')
  },
})

ReactDOM.createRoot(document.getElementById('root')).render(
  <React.StrictMode>
    <App />
  </React.StrictMode>
)
